version: "3.4"
services:
  mediamtx:
    image: bluenviron/mediamtx:1.2.1@sha256:accd41235d508f8280c840294c5f82547fc9cc007eb24a5ce64d89b18713db85
    container_name: mediamtx
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${MEDIAMTX_CONFIG_DIR}/mediamtx.yml
        target: /mediamtx.yml
      - ${MEDIAMTX_RECORDINGS_DIR}:/recordings
    ports:
      - 8554:8554
      - 8890:8890/udp 
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 9997:9997